version: "3"

services:
  nginx-stream-proxy-protocol-v2:
    container_name: nginx-proxy-v2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./log:/usr/local/nginx/logs/
    ports:
      - "80:80"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: 100m
    restart: always
